### ISSUE TITLE
ue4-docker setup wont work with Hyper-V server 2019

### ISSUE THREAD

**Issue by muit** [adamrehn/ue4-docker#119]
Output of the `ue4-docker info` command:
```
ue4-docker version:         0.0.73 (latest available version is 0.0.73)
Operating system:           Hyper-V Server 2019  Version 1809 (OS Build 17763.737)
Docker daemon version:      19.03.13
NVIDIA Docker supported:    No
Maximum image size:         20GB
Available disk space:       1.68 TiB
Total system memory:        15.95 GiB physical, 18.83 GiB virtual
Number of processors:       8 physical, 16 logical
```

Additional details:

While setting up docker on windows server, (specifically hyper-v windows server 2019), it will display the same warning as if it was Win10 or Mac.

```bash
muit@BIG-LIFTER C:\>ue4-docker setup
Manual configuration is required under Windows 10 and macOS. Automatic configuration is not available.
```

This doesn't look like the intended behavior since Hyper-V server is sort of an stripped version of windows server.
I understand this is an edge case though, thank you for your work like always!

**Comment by muit** [comment]
Setup failed after the fix with:
```
Starting a container to copy DLL files from...
Traceback (most recent call last):
  File "c:\python39\lib\site-packages\docker\api\client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "c:\python39\lib\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localnpipe/v1.40/containers/2215ae479fa163a2bbd965e42aad969f64686e9ee49d189144648c691614803e/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\Scripts\ue4-docker.exe\__main__.py", line 7, in <module>
  File "c:\python39\lib\site-packages\ue4docker\main.py", line 86, in main
    COMMANDS[command]['function']()
  File "c:\python39\lib\site-packages\ue4docker\setup_cmd.py", line 152, in setup
    _setupWindowsServer()
  File "c:\python39\lib\site-packages\ue4docker\setup_cmd.py", line 117, in _setupWindowsServer
    container = DockerUtils.start(
  File "c:\python39\lib\site-packages\ue4docker\infrastructure\DockerUtils.py", line 66, in start
    return client.containers.run(image, command, detach=True, **kwargs)
  File "c:\python39\lib\site-packages\docker\models\containers.py", line 818, in run
    container.start()
  File "c:\python39\lib\site-packages\docker\models\containers.py", line 404, in start
    return self.client.api.start(self.id, **kwargs)
  File "c:\python39\lib\site-packages\docker\utils\decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "c:\python39\lib\site-packages\docker\api\container.py", line 1111, in start
    self._raise_for_status(res)
  File "c:\python39\lib\site-packages\docker\api\client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "c:\python39\lib\site-packages\docker\errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error for http+docker://localnpipe/v1.40/containers/2215ae479fa163a2bbd965e42aad969f64686e9ee49d189144648c691614803e/start: Internal Server Error ("hcsshim::CreateComputeSystem 2215ae479fa163a2bbd965e42aad969f64686e9ee49d189144648c691614803e: The request is not supported.
(extra info: {"SystemType":"Container","Name":"2215ae479fa163a2bbd965e42aad969f64686e9ee49d189144648c691614803e","Owner":"docker","VolumePath":"\\\\?\\Volume{401c1ebe-fee7-4036-bfd6-6d608093da0a}","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\docker\\windowsfilter\\2215ae479fa163a2bbd965e42aad969f64686e9ee49d189144648c691614803e","Layers":[{"ID":"145170e9-a181-5cc5-ad55-958a408e2be8","Path":"C:\\ProgramData\\docker\\windowsfilter\\b5de3416ad2831343800f676ef6cf7412fe22d7b9c3febdf8530204863f99f1a"},{"ID":"51e4b1a9-c344-5b96-830b-9ecaa3bd05e5","Path":"C:\\ProgramData\\docker\\windowsfilter\\f06dff36b0540b2227859a182cf04ff166aae38d6841c33deea5960da08925c7"}],"HostName":"2215ae479fa1","MappedDirectories":[{"HostPath":"C:\\Windows\\System32","ContainerPath":"C:\\dlldir","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false}],"HvPartition":false,"EndpointList":["5286270E-F084-4B26-84C6-84F441C1C042"],"AllowUnqualifiedDNSQuery":true})")
```

I don't know if it's related

**Comment by muit** [comment]
https://github.com/MicrosoftDocs/Virtualization-Documentation/issues/945
According to this, Hyper-V server doesnt support starting containers 🤦 

So this may not make sense after all

**Comment by adamrehn** [comment]
Based on the discussion thread on that issue, it's clear that Hyper-V server does not support running containers and there is no intention of adding that functionality anytime soon, so I'm going to close this issue for now. We can certainly revisit Hyper-V server as a host platform if container support is ever added in the future though.
