### ISSUE TITLE
ModuleNotFoundError: No module named 'setuptools_rust'

### ISSUE THREAD

**Issue by domgreen** [adamrehn/ue4-docker#160]
Output of the `ue4-docker info` command:

```
ue4-docker version:         0.0.82 (latest available version is 0.0.82)
Operating system:           Linux (Ubuntu 20.04.1 LTS, 5.4.0-42-generic)
Docker daemon version:      20.10.6
NVIDIA Docker supported:    Yes
Maximum image size:         No limit detected
Available disk space:       393.7 GiB
Total system memory:        62.42 GiB physical, 2 GiB virtual
Number of processors:       24 physical, 48 logical
```

Additional details:

- Are you accessing the network through a proxy server? **No**

(The rest of the issue description goes here. If you're reporting a problem with building container images, be sure to include the full output of the `ue4-docker build` command, including the initial output lines that display the command line parameters used to invoke the build. If you're making a feature request, you can remove the template contents entirely, since the `ue4-docker info` output and related information is only needed for helping diagnose and reproduce bugs.)

```
sudo ue4-docker build 4.26.2
```

```
[ue4-docker build] Building image "adamrehn/ue4-full:custom-opengl"...                                                                                               [190/839]
Sending build context to Docker daemon  9.216kB                                                                                                                               
Step 1/35 : ARG NAMESPACE                                                                                                                                                     
Step 2/35 : ARG TAG                                                                                                                                                           
Step 3/35 : ARG PREREQS_TAG                                                                                                                                                   
Step 4/35 : ARG UE4CLI_VERSION="ue4cli>=0.0.45"                                                                                                                               
Step 5/35 : ARG CONAN_UE4CLI_VERSION="conan-ue4cli>=0.0.27"                                                                                                                   
Step 6/35 : FROM ${NAMESPACE}/ue4-source:${TAG}-${PREREQS_TAG} AS builder                                                                                                     
 ---> 9e0b842eacb7                                                                                                                                                            
Step 7/35 : ARG UE4CLI_VERSION                                                                                                                                                
 ---> Using cache                                                                                                                                                             
 ---> 1a21ec1aea24                                                                                                                                                            
Step 8/35 : ARG CONAN_UE4CLI_VERSION                                                                                                                                          
 ---> Using cache                                                                                                                                                             
 ---> 933ec5d887aa                                                                                                                                                            
Step 9/35 : USER root                  
 ---> Using cache                                                                                                                                                             
 ---> 3b295e36e78f                                                                                                                                                            
Step 10/35 : RUN pip3 install setuptools wheel && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large 
filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''                                                                  
 ---> Using cache                                                                                                                                                             
 ---> d96c0008ffd6
Step 11/35 : RUN pip3 install "$UE4CLI_VERSION" "$CONAN_UE4CLI_VERSION" && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && e
cho 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''
 ---> Running in 6bf77b25e8ec

... 


            =============================DEBUG ASSISTANCE==========================
            If you are seeing an error here please try the following to
            successfully install cryptography:
     
            Upgrade to the latest pip and try again. This will fix errors for most
            users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
            =============================DEBUG ASSISTANCE==========================
     
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-tj1edq5y/cryptography/setup.py", line 14, in <module>
        from setuptools_rust import RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'
```

**Comment by domgreen** [comment]
This now seems to have been fixed upstream and I can build out the containers now :+1:

**Comment by domgreen** [comment]
Actually hitting this issue again trying to create a custom container image

**Comment by domgreen** [comment]
```
sudo ue4-docker build -repo https://github.com/xxx/UnrealEngine -branch test_branch -user domgreen custom
```
```
ue4-docker version:         0.0.77 (latest available version is 0.0.85)
Operating system:           Linux (Ubuntu 20.04.1 LTS, 5.4.0-42-generic)
Docker daemon version:      20.10.6
NVIDIA Docker supported:    Yes
Maximum image size:         No limit detected
Available disk space:       32.13 GiB
Total system memory:        62.42 GiB physical, 2 GiB virtual
Number of processors:       24 physical, 48 logical
```

**Comment by domgreen** [comment]
Actually upgrading from `0.0.77` to `0.0.85` fixes this :sweat_smile:
