### ISSUE TITLE
No module named `secrets`

### ISSUE THREAD

**Issue by SyedAman** [adamrehn/ue4-docker#2]
Getting this error right here when I try to run` build.py.`

```
D:\Downloads\ue4-docker>python build.py 4.19.2
Traceback (most recent call last):
  File "build.py", line 4, in <module>
    from utils import *
  File "D:\Downloads\ue4-docker\utils\__init__.py", line 1, in <module>
    from .CredentialEndpoint import CredentialEndpoint
  File "D:\Downloads\ue4-docker\utils\CredentialEndpoint.py", line 1, in <module>
    import logging, multiprocessing, platform, secrets, time, urllib.parse
ImportError: No module named 'secrets'
```

**Comment by SyedAman** [comment]
I created a `secrets.py` file but then got:

```
Traceback (most recent call last):
  File "build.py", line 96, in <module>
    endpoint = CredentialEndpoint(username, password)
  File "D:\Downloads\ue4-docker\utils\CredentialEndpoint.py", line 16, in __init__
    self.token = secrets.token_hex(16)
AttributeError: module 'secrets' has no attribute 'token_hex'
```

**Comment by SyedAman** [comment]
Hmmm... according to https://docs.python.org/3/library/secrets.html

It's new in `Python 3.6.` I will update my Python and test this and let everyone know if this was the fix.

**Comment by adamrehn** [comment]
Oops, I'd missed that detail before. Thanks for letting me know, I've updated the README to state that Python 3.6 is needed rather than just 3.x.
