### ISSUE TITLE
Failed requirement 'boost/1.67.0@conan/stable' from 'MediaIPC-ue4/0.0.2@adamrehn/4.26'

### ISSUE THREAD

**Issue by domenicoCappello** [adamrehn/ue4-docker#201]
Output of the `ue4-docker info` command:

```
ue4-docker version:         0.0.90 (latest available version is 0.0.90)
Operating system:           Linux (Ubuntu 20.04.3 LTS, 5.10.0-1045-oem)
Docker daemon version:      20.10.8
NVIDIA Docker supported:    No
Maximum image size:         No limit detected
Available disk space:       85.74 GiB
Total system memory:        31.14 GiB physical, 2 GiB virtual
Number of processors:       8 physical, 16 logical
```

Additional details:

- Are you accessing the network through a proxy server? **No**

(The rest of the issue description goes here. If you're reporting a problem with building container images, be sure to include the full output of the `ue4-docker build` command, including the initial output lines that display the command line parameters used to invoke the build. If you're making a feature request, you can remove the template contents entirely, since the `ue4-docker info` output and related information is only needed for helping diagnose and reproduce bugs.)

The following command fails to build the ue4-full image:
`ue4-docker build 4.26.2 --cuda=10.2 --no-engine --monitor --exclude ddc --exclude debug`

Output:
```
[ue4-docker build] COMMAND-LINE INVOCATION:
[ue4-docker build] ['ue4-docker', '4.26.2', '--cuda=10.2', '--no-engine', '--monitor', '--exclude', 'ddc', '--exclude', 'debug']

[ue4-docker build] UNREAL ENGINE VERSION SETTINGS:
[ue4-docker build] Custom build:  No
[ue4-docker build] Release:       4.26.2
[ue4-docker build] Repository:    https://github.com/EpicGames/UnrealEngine.git
[ue4-docker build] Branch/tag:    4.26.2-release

[ue4-docker build] ADVANCED CONFIGURATION OPTIONS:
[ue4-docker build] excluded_components: {"ddc": true, "debug": true, "templates": false}

[ue4-docker build] LINUX CONTAINER SETTINGS
[ue4-docker build] Building GPU-enabled images compatible with NVIDIA Docker (CUDA 10.2 + OpenGL support).

[ue4-docker build] GENERAL SETTINGS
[ue4-docker build] Excluding the following Engine components:
[ue4-docker build] - Debug symbols
[ue4-docker build] - Derived Data Cache (DDC)
[ue4-docker build] Not building the ue4-source image, no Git credentials required.
[ue4-docker build] [2021-09-09 14:30:07] [Available disk: 85.74 GiB] [Available memory: 1.17 GiB physical, 1.71 GiB virtual] [CPU usage: 0.00%]

[ue4-docker build] Image "adamrehn/ue4-build-prerequisites:cudagl10.2" exists and rebuild not requested, skipping build.

[ue4-docker build] Image "adamrehn/ue4-source:4.26.2-cudagl10.2" exists and rebuild not requested, skipping build.

[ue4-docker build] User specified `--no-engine`, skipping ue4-engine image build.

[ue4-docker build] Image "adamrehn/ue4-minimal:4.26.2-cudagl10.2" exists and rebuild not requested, skipping build.

[ue4-docker build] Building image "adamrehn/ue4-full:4.26.2-cudagl10.2"...
Sending build context to Docker daemon  8.192kB
Step 1/34 : ARG UE4CLI_VERSION="ue4cli>=0.0.45"
Step 2/34 : ARG CONAN_UE4CLI_VERSION="conan-ue4cli>=0.0.27"
Step 3/34 : ARG NAMESPACE
Step 4/34 : ARG TAG
Step 5/34 : ARG PREREQS_TAG
Step 6/34 : FROM ${NAMESPACE}/ue4-source:${TAG}-${PREREQS_TAG} AS conan
 ---> cab314adcff1
Step 7/34 : ARG UE4CLI_VERSION
 ---> Using cache
 ---> 93b1b610ebc5
Step 8/34 : ARG CONAN_UE4CLI_VERSION
 ---> Using cache
 ---> 2ad807c8fa57
Step 9/34 : USER root
 ---> Using cache
 ---> 2b3ac4a06672
Step 10/34 : RUN pip3 install --upgrade pip setuptools wheel && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''
 ---> Using cache
 ---> 0ed7995b2789
Step 11/34 : RUN pip3 install "$UE4CLI_VERSION" "$CONAN_UE4CLI_VERSION" && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''
 ---> Using cache
 ---> 465310121da1
Step 12/34 : USER ue4
 ---> Using cache
 ---> 4fbbe3148784
Step 13/34 : RUN ue4 setroot /home/ue4/UnrealEngine && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''
 ---> Using cache
 ---> d1f069425f3f
Step 14/34 : RUN ue4 conan generate && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''
 ---> Using cache
 ---> b522492dafe5
Step 15/34 : FROM ${NAMESPACE}/ue4-minimal:${TAG}-${PREREQS_TAG}
 ---> 4c480794a234
Step 16/34 : ARG UE4CLI_VERSION
 ---> Using cache
 ---> 2937291d5c29
Step 17/34 : ARG CONAN_UE4CLI_VERSION
 ---> Using cache
 ---> d4a1d48416c0
Step 18/34 : RUN git clone "https://github.com/adamrehn/UE4Capture.git" /home/ue4/UE4Capture && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''
 ---> Using cache
 ---> 52e951023c73
Step 19/34 : USER root
 ---> Using cache
 ---> 9364c2ba8bac
Step 20/34 : RUN apt-get update && apt-get install -y --no-install-recommends cmake && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''
 ---> Using cache
 ---> f9ff4538e4b9
Step 21/34 : RUN pip3 install --upgrade pip setuptools wheel && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''
 ---> Using cache
 ---> f16a1c096849
Step 22/34 : RUN pip3 install "$UE4CLI_VERSION" "$CONAN_UE4CLI_VERSION" ue4-ci-helpers && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''
 ---> Using cache
 ---> c76c13ae5a5f
Step 23/34 : USER ue4
 ---> Using cache
 ---> 92e2a27144ea
Step 24/34 : ENV UE4CLI_CONFIG_DIR /home/ue4/.config/ue4cli
 ---> Using cache
 ---> 2c1d13b3262a
Step 25/34 : COPY --from=conan --chown=ue4:ue4 /home/ue4/.conan /home/ue4/.conan
 ---> Using cache
 ---> a6fde63bcc00
Step 26/34 : RUN ue4 setroot /home/ue4/UnrealEngine && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''
 ---> Using cache
 ---> bdcd1a7e6d65
Step 27/34 : RUN ue4 conan generate --profile-only && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''
 ---> Using cache
 ---> 7331be5e7ff2
Step 28/34 : RUN ue4 conan build MediaIPC-ue4 && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''
 ---> Running in 5b9330d350c3
Using default profile for host platform "ue4.26-Linux-x86_64-unknown-linux-gnu"
Updating the recipe cache...

Unzipping 50.0KB


Recipe cache updated.
Exporting package recipes from the following source directories:
- /home/ue4/.config/conan-ue4cli/recipes
- /home/ue4/UnrealEngine

Using user-specified engine root: /home/ue4/UnrealEngine
['conan', 'export', '/home/ue4/.config/conan-ue4cli/recipes/proj-ue4/4.9.3/conanfile.py', 'proj-ue4/4.9.3@adamrehn/4.26']
Exporting recipe for package "proj-ue4/4.9.3@adamrehn/4.26"...
Exporting package recipe
proj-ue4/4.9.3@adamrehn/4.26: A new conanfile.py version was exported
proj-ue4/4.9.3@adamrehn/4.26: Folder: /home/ue4/.conan/data/proj-ue4/4.9.3/adamrehn/4.26/export
proj-ue4/4.9.3@adamrehn/4.26: Exported revision: 7c259b2dd130d0a9095bad11e159db2d
['conan', 'export', '/home/ue4/.config/conan-ue4cli/recipes/gdal-ue4/2.4.0/conanfile.py', 'gdal-ue4/2.4.0@adamrehn/4.26']
Exporting recipe for package "gdal-ue4/2.4.0@adamrehn/4.26"...
Exporting package recipe
gdal-ue4/2.4.0@adamrehn/4.26: A new conanfile.py version was exported
gdal-ue4/2.4.0@adamrehn/4.26: Folder: /home/ue4/.conan/data/gdal-ue4/2.4.0/adamrehn/4.26/export
gdal-ue4/2.4.0@adamrehn/4.26: Exported revision: f4199bb3df9a84dd427bd99ab142d95d
Exporting recipe for package "python-ue4/3.6.8@adamrehn/4.26"...
['conan', 'export', '/home/ue4/.config/conan-ue4cli/recipes/python-ue4/3.6.8/conanfile.py', 'python-ue4/3.6.8@adamrehn/4.26']
Exporting package recipe
python-ue4/3.6.8@adamrehn/4.26: A new conanfile.py version was exported
python-ue4/3.6.8@adamrehn/4.26: Folder: /home/ue4/.conan/data/python-ue4/3.6.8/adamrehn/4.26/export
python-ue4/3.6.8@adamrehn/4.26: Exported revision: 4b8d92e06fd5a0a93dcd2aeb6f2bbde4
Exporting recipe for package "mergetiff-ue4/0.0.6@adamrehn/4.26"...
['conan', 'export', '/home/ue4/.config/conan-ue4cli/recipes/mergetiff-ue4/0.0.6/conanfile.py', 'mergetiff-ue4/0.0.6@adamrehn/4.26']
Exporting package recipe
mergetiff-ue4/0.0.6@adamrehn/4.26: A new conanfile.py version was exported
mergetiff-ue4/0.0.6@adamrehn/4.26: Folder: /home/ue4/.conan/data/mergetiff-ue4/0.0.6/adamrehn/4.26/export
mergetiff-ue4/0.0.6@adamrehn/4.26: Exported revision: c1c6f72cbabb059c2450415ab73c1a54
Exporting recipe for package "grpc-ue4/1.30.2@adamrehn/4.26"...
['conan', 'export', '/home/ue4/.config/conan-ue4cli/recipes/grpc-ue4/1.30.2/conanfile.py', 'grpc-ue4/1.30.2@adamrehn/4.26']
Exporting package recipe
grpc-ue4/1.30.2@adamrehn/4.26 exports: Copied 3 '.py' files: conanfile.py, __init__.py, grpc_helper.py
grpc-ue4/1.30.2@adamrehn/4.26: A new conanfile.py version was exported
grpc-ue4/1.30.2@adamrehn/4.26: Folder: /home/ue4/.conan/data/grpc-ue4/1.30.2/adamrehn/4.26/export
grpc-ue4/1.30.2@adamrehn/4.26: Exported revision: f26cd90937712439c2abde80ef6d04de
['conan', 'export', '/home/ue4/.config/conan-ue4cli/recipes/grpc-ue4/1.16.0/conanfile.py', 'grpc-ue4/1.16.0@adamrehn/4.26']
Exporting recipe for package "grpc-ue4/1.16.0@adamrehn/4.26"...
Exporting package recipe
grpc-ue4/1.16.0@adamrehn/4.26 exports: Copied 3 '.py' files: conanfile.py, __init__.py, grpc_helper.py
grpc-ue4/1.16.0@adamrehn/4.26: A new conanfile.py version was exported
grpc-ue4/1.16.0@adamrehn/4.26: Folder: /home/ue4/.conan/data/grpc-ue4/1.16.0/adamrehn/4.26/export
grpc-ue4/1.16.0@adamrehn/4.26: Exported revision: da3287bcba9efc9a1c6b1ee0b5fc9492
Exporting recipe for package "protobuf-ue4/3.6.1@adamrehn/4.26"...
['conan', 'export', '/home/ue4/.config/conan-ue4cli/recipes/protobuf-ue4/3.6.1/conanfile.py', 'protobuf-ue4/3.6.1@adamrehn/4.26']
Exporting package recipe
protobuf-ue4/3.6.1@adamrehn/4.26: A new conanfile.py version was exported
protobuf-ue4/3.6.1@adamrehn/4.26: Folder: /home/ue4/.conan/data/protobuf-ue4/3.6.1/adamrehn/4.26/export
protobuf-ue4/3.6.1@adamrehn/4.26: Exported revision: 0a22da5916fec7197a0040769a492a41
['conan', 'export', '/home/ue4/.config/conan-ue4cli/recipes/protobuf-ue4/3.12.3/conanfile.py', 'protobuf-ue4/3.12.3@adamrehn/4.26']
Exporting recipe for package "protobuf-ue4/3.12.3@adamrehn/4.26"...
Exporting package recipe
protobuf-ue4/3.12.3@adamrehn/4.26: A new conanfile.py version was exported
protobuf-ue4/3.12.3@adamrehn/4.26: Folder: /home/ue4/.conan/data/protobuf-ue4/3.12.3/adamrehn/4.26/export
protobuf-ue4/3.12.3@adamrehn/4.26: Exported revision: 400570516b73f9834883d70f771161f5
['conan', 'export', '/home/ue4/.config/conan-ue4cli/recipes/playfab-gsdk-ue4/0.6.190103/conanfile.py', 'playfab-gsdk-ue4/0.6.190103@adamrehn/4.26']
Exporting recipe for package "playfab-gsdk-ue4/0.6.190103@adamrehn/4.26"...
Exporting package recipe
playfab-gsdk-ue4/0.6.190103@adamrehn/4.26 exports_sources: Copied 1 '.txt' file: CMakeLists.txt
playfab-gsdk-ue4/0.6.190103@adamrehn/4.26: A new conanfile.py version was exported
playfab-gsdk-ue4/0.6.190103@adamrehn/4.26: Folder: /home/ue4/.conan/data/playfab-gsdk-ue4/0.6.190103/adamrehn/4.26/export
playfab-gsdk-ue4/0.6.190103@adamrehn/4.26: Exported revision: 434c5c7b5cb057e31bfcb4f5601705bf
['conan', 'export', '/home/ue4/.config/conan-ue4cli/recipes/geos-ue4/3.6.3/conanfile.py', 'geos-ue4/3.6.3@adamrehn/4.26']
Exporting recipe for package "geos-ue4/3.6.3@adamrehn/4.26"...
Exporting package recipe
geos-ue4/3.6.3@adamrehn/4.26: A new conanfile.py version was exported
geos-ue4/3.6.3@adamrehn/4.26: Folder: /home/ue4/.conan/data/geos-ue4/3.6.3/adamrehn/4.26/export
geos-ue4/3.6.3@adamrehn/4.26: Exported revision: c6a9297c67094bc3469f5c39db5bc748
Exporting recipe for package "cares-ue4/1.16.1@adamrehn/4.26"...
['conan', 'export', '/home/ue4/.config/conan-ue4cli/recipes/cares-ue4/1.16.1/conanfile.py', 'cares-ue4/1.16.1@adamrehn/4.26']
Exporting package recipe
cares-ue4/1.16.1@adamrehn/4.26: A new conanfile.py version was exported
cares-ue4/1.16.1@adamrehn/4.26: Folder: /home/ue4/.conan/data/cares-ue4/1.16.1/adamrehn/4.26/export
cares-ue4/1.16.1@adamrehn/4.26: Exported revision: c5d76be28af38b524a7d5c905d0d8326
Exporting recipe for package "cares-ue4/1.13.0@adamrehn/4.26"...
['conan', 'export', '/home/ue4/.config/conan-ue4cli/recipes/cares-ue4/1.13.0/conanfile.py', 'cares-ue4/1.13.0@adamrehn/4.26']
Exporting package recipe
cares-ue4/1.13.0@adamrehn/4.26: A new conanfile.py version was exported
cares-ue4/1.13.0@adamrehn/4.26: Folder: /home/ue4/.conan/data/cares-ue4/1.13.0/adamrehn/4.26/export
cares-ue4/1.13.0@adamrehn/4.26: Exported revision: e88d6c749d3f4398eb0e18d16d3fe155
Exporting recipe for package "MediaIPC-ue4/0.0.2@adamrehn/4.26"...
['conan', 'export', '/home/ue4/.config/conan-ue4cli/recipes/MediaIPC-ue4/0.0.2/conanfile.py', 'MediaIPC-ue4/0.0.2@adamrehn/4.26']
Exporting package recipe
MediaIPC-ue4/0.0.2@adamrehn/4.26: A new conanfile.py version was exported
MediaIPC-ue4/0.0.2@adamrehn/4.26: Folder: /home/ue4/.conan/data/MediaIPC-ue4/0.0.2/adamrehn/4.26/export
MediaIPC-ue4/0.0.2@adamrehn/4.26: Exported revision: b4d1fa457e93fdcf3cb89b6c4b1f39cc
The following packages will be built:
- MediaIPC-ue4/0.0.2

Building package "MediaIPC-ue4/0.0.2@adamrehn/4.26"...
['conan', 'install', 'MediaIPC-ue4/0.0.2@adamrehn/4.26', '--profile=ue4.26-Linux-x86_64-unknown-linux-gnu', '--build=missing']
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=clang
compiler.libcxx=libc++
compiler.version=10
os=Linux
os_build=Linux
[options]
[build_requires]
*: toolchain-wrapper/ue4@adamrehn/4.26
[env]
UNREAL_ENGINE_VERSION=4.26
boost/1.67.0@conan/stable: Not found in local cache, looking in remotes...
boost/1.67.0@conan/stable: Trying with 'conancenter'...
ERROR: Failed requirement 'boost/1.67.0@conan/stable' from 'MediaIPC-ue4/0.0.2@adamrehn/4.26'
ERROR: Unable to find 'boost/1.67.0@conan/stable' in remotes
Traceback (most recent call last):
  File "/usr/local/bin/ue4", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/ue4cli/cli.py", line 222, in main
    SUPPORTED_COMMANDS[command]['action'](manager, args)
  File "/usr/local/lib/python3.6/dist-packages/conan_ue4cli/main.py", line 48, in main
    SUBCOMMANDS[subcommand]['function'](manager, args[1:])
  File "/usr/local/lib/python3.6/dist-packages/conan_ue4cli/commands/build.py", line 130, in build
    builder.build(name, version, args.options if args.options is not None else [])
  File "/usr/local/lib/python3.6/dist-packages/conan_ue4cli/common/PackageBuilder.py", line 45, in build
    self._executor.execute(command, cwd=tempDir, check=True)
  File "/usr/local/lib/python3.6/dist-packages/conan_ue4cli/common/CommandExecutor.py", line 19, in execute
    return subprocess.run(command, **kwargs).returncode == 0
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['conan', 'install', 'MediaIPC-ue4/0.0.2@adamrehn/4.26', '--profile=ue4.26-Linux-x86_64-unknown-linux-gnu', '--build=missing']' returned non-zero exit status 1.
The command '/bin/sh -c ue4 conan build MediaIPC-ue4 && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''' returned a non-zero code: 1
[ue4-docker build] Error: failed to build image "adamrehn/ue4-full:4.26.2-cudagl10.2".
```

Any help would be much appreciated, thanks.

**Comment by slonopotamus** [comment]
@adamrehn I'm not very aware of all this conan stuff. Do you have any ideas what goes wrong here?

**Comment by slonopotamus** [comment]
Okay, that MediaIPC -> Boost dependency comes from here: https://github.com/adamrehn/MediaIPC/blob/master/conanfile.txt#L2

Now the question is: why Boost is missing.

**Comment by slonopotamus** [comment]
The oldest Boost available through conan is 1.69: 
https://conan.io/center/boost


It looks like, older versions were removed somewhere around https://github.com/conan-io/conan-center-index/pull/2936?

**Comment by slonopotamus** [comment]
@domenicoCappello as a workaround, maybe you'll be happy with ue4-minimal image (that you've already built)? `--no-full` command-line arg suppresses building of ue4-full on further ue4-docker invocations.

**Comment by slonopotamus** [comment]
Do we actually need that MediaIPC lib (and/or conan stuff at all)?

**Comment by domenicoCappello** [comment]
Thank you @slonopotamus

**Comment by Herajy** [comment]
I'm also facing the same issues recently, but I also need MediaIPC so the above fix does not work for me.  why not to fix the issue by fixing boost version in the cannon file here:
https://github.com/adamrehn/ue4-conan-recipes/blob/master/MediaIPC-ue4/0.0.2/conanfile.py? That is to change boost version to 1.69

**Comment by slonopotamus** [comment]
> why not to fix the issue by fixing boost version in the cannon file here

I've listed reasons in #202.

Anyway, I've also created https://github.com/adamrehn/ue4-conan-recipes/pull/9

**Comment by adamrehn** [comment]
Thanks for that @slonopotamus, I've merged that ue4-conan-recipes PR now, along with #202. I've also fixed this for anyone building MediaIPC from source without UE4: https://github.com/adamrehn/MediaIPC/commit/701ab049348cbde515bfa1d20e7cc6c937361022

**Comment by Herajy** [comment]
Many thanks for the fix. For building MediaIPC from source, still conon is not able to find 'boost/1.69..0@conan/stable'. Seems user name/channel have been removed from boost release names at conancenter.  Trying conan search boost* -r=conancenter, I got:
Existing package recipes:

boost/1.69.0
boost/1.70.0
boost/1.71.0
boost/1.72.0
boost/1.73.0
boost/1.74.0
boost/1.75.0
boost/1.76.0
boost/1.77.0

So to make MediaIPC finds boost package on cannon, 'boost/1.69..0@conan/stable' needs to be replaced by just boost/1.69.0

This fix will be useful for someone who will build mediaIPC from source

**Comment by adamrehn** [comment]
@Herajy thanks for pointing that out! The Conan docs indicate that [the user/channel suffixes have indeed been removed for ConanCenter](https://docs.conan.io/en/latest/uploading_packages/remotes.html#conancenter), and that the suffixed package names only work for the older (now deprecated) legacy remote. I've updated MediaIPC to reflect this in https://github.com/adamrehn/MediaIPC/commit/009c8008222101c247dbeecec7cf940dc783dbf5.

**Comment by Herajy** [comment]
Many thanks @adamrehn for adjusting it
