### ISSUE TITLE
Git username and password has updated to token

### ISSUE THREAD

**Issue by Rafearl** [adamrehn/ue4-docker#258]
Output of the `ue4-docker info` command:

```
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/usr/local/bin/ue4-docker", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/ue4docker/main.py", line 112, in main
    COMMANDS[command]["function"]()
  File "/usr/local/lib/python3.8/dist-packages/ue4docker/info.py", line 42, in info
    _formatSize(shutil.disk_usage(rootDir).free)
  File "/usr/lib/python3.8/shutil.py", line 1258, in disk_usage
    st = os.statvfs(path)
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/docker'

```

Additional details:

- Are you accessing the network through a proxy server? No

Running "ue4-docker build 4.27.2" I got the following after entering the deprecated Git username and password 

````
 => ERROR [ 4/13] RUN mkdir /home/ue4/UnrealEngine &&  cd /home/ue4/UnrealEngine &&  git init &&  git remote add   1.9s
------
 > [ 4/13] RUN mkdir /home/ue4/UnrealEngine &&  cd /home/ue4/UnrealEngine &&    git init &&     git remote add origin "https://github.com/EpicGames/UnrealEngine.git" &&        git fetch --progress --depth 1 origin "4.27.2-release" &&      git checkout FETCH_HEAD && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo '':
#8 0.539 Initialized empty Git repository in /home/ue4/UnrealEngine/.git/
#8 1.874 remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.
#8 1.874 remote: Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information.
#8 1.874 fatal: Authentication failed for 'https://github.com/EpicGames/UnrealEngine.git/'
````

Is there any way to go around this?

**Comment by TBBle** [comment]
Specifically, on the [page linked from the error](https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/), see the first dot-point under "What you need to do today".

**Comment by wohlbier** [comment]
I'm hitting this issue. I have a token, and I've verified that I can clone https://github.com/EpicGames/UnrealEngine.git/ using the token. But when I run I get:
```
[jgwohlbier@etc-gpu-09 ue4-docker]$ ue4-docker build 4.27.0 --cuda=11.4.0 
[ue4-docker build] COMMAND-LINE INVOCATION:
[ue4-docker build] ['ue4-docker', '4.27.0', '--cuda=11.4.0']

[ue4-docker build] UNREAL ENGINE VERSION SETTINGS:
[ue4-docker build] Custom build:  No
[ue4-docker build] Release:       4.27.0
[ue4-docker build] Repository:    https://github.com/EpicGames/UnrealEngine.git
[ue4-docker build] Branch/tag:    4.27.0-release

[ue4-docker build] ADVANCED CONFIGURATION OPTIONS:
[ue4-docker build] excluded_components: {"ddc": false, "debug": false, "templates": false}

[ue4-docker build] LINUX CONTAINER SETTINGS
[ue4-docker build] Base OS image: nvidia/cudagl:11.4.0-devel-ubuntu18.04

[ue4-docker build] GENERAL SETTINGS
[ue4-docker build] Build targets: build-prerequisites full minimal source
[ue4-docker build] Changelist override: 17155196
[ue4-docker build] Not excluding any Engine components.

Retrieving the Git credentials that will be used to clone the UE4 repo
Username: wohlbier
Password: 


[ue4-docker build] Image "adamrehn/ue4-build-prerequisites:cudagl11.4.0-ubuntu18.04" exists and rebuild not requested, skipping build.

[ue4-docker build] Building image "adamrehn/ue4-source:4.27.0-cudagl11.4.0-ubuntu18.04"...
[+] Building 1.5s (8/17)                                                        
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 4.50kB                                     0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 87B                                           0.0s
 => [internal] load metadata for docker.io/adamrehn/ue4-build-prerequisit  0.0s
 => [ 1/13] FROM docker.io/adamrehn/ue4-build-prerequisites:cudagl11.4.0-  0.0s
 => [internal] load build context                                          0.0s
 => => transferring context: 377B                                          0.0s
 => CACHED [ 2/13] COPY --chown=ue4:ue4 git-credential-helper-endpoint.sh  0.0s
 => [ 3/13] RUN chmod +x /tmp/git-credential-helper-endpoint.sh && echo '  0.3s
 => ERROR [ 4/13] RUN mkdir /home/ue4/UnrealEngine &&  cd /home/ue4/Unrea  1.0s
------                                                                          
 > [ 4/13] RUN mkdir /home/ue4/UnrealEngine &&  cd /home/ue4/UnrealEngine &&   git init &&      git remote add origin "https://github.com/EpicGames/UnrealEngine.git" &&        git fetch --progress --depth 1 origin "4.27.0-release" &&      git checkout FETCH_HEAD && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo '':
#8 0.414 Initialized empty Git repository in /home/ue4/UnrealEngine/.git/
#8 0.937 remote: Support for password authentication was removed on August 13, 2021.
#8 0.937 remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
#8 0.937 fatal: Authentication failed for 'https://github.com/EpicGames/UnrealEngine.git/'
------
executor failed running [/bin/sh -c mkdir /home/ue4/UnrealEngine && 	cd /home/ue4/UnrealEngine && 	git init && 	git remote add origin "$GIT_REPO" && 	git fetch --progress --depth 1 origin "$GIT_BRANCH" && 	git checkout FETCH_HEAD && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo '']: exit code: 128
[ue4-docker build] Error: failed to build image "adamrehn/ue4-source:4.27.0-cudagl11.4.0-ubuntu18.04".
```

```
[jgwohlbier@etc-gpu-09 ue4-docker]$ ue4-docker info
ue4-docker version:         0.0.102 (latest available version is 0.0.102)
Operating system:           Linux (Red Hat Enterprise Linux 8.7 (Ootpa), 4.18.0-425.3.1.el8.x86_64)
Docker daemon version:      20.10.21
NVIDIA Docker supported:    Yes
Maximum image size:         No limit detected
Available disk space:       3.99 TiB
Total system memory:        187.28 GiB physical, 0 bytes virtual
CPU:                        20 physical, 40 logical (x86_64)
```

**Comment by TBBle** [comment]
I'd suggest opening a new issue for this, since if you're not putting your password into the script, then something has gone wrong that needs closer inspection, while this issue was "user was putting in a password instead of a token, and GitHub stopped supporting tokens".

That said, we're still prompting for `Password:`, perhaps that should be `Password or access token:`.

**Comment by wohlbier** [comment]
Ok. Thanks.
