### ISSUE TITLE
Windows Server https://mcr.microsoft.com/v2/windowsfamily/windows/tags/list no longer available

### ISSUE THREAD

**Issue by hach-que** [adamrehn/ue4-docker#28]
When running `ue4-docker setup` inside a Packer script:

```
    googlecompute:
    googlecompute: Traceback (most recent call last):
    googlecompute: SERVICE_NAME: docker
    googlecompute:         TYPE               : 10  WIN32_OWN_PROCESS
    googlecompute:         STATE              : 3  STOP_PENDING
    googlecompute:                                 (NOT_STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
    googlecompute:         WIN32_EXIT_CODE    : 0  (0x0)
    googlecompute:         SERVICE_EXIT_CODE  : 0  (0x0)
    googlecompute:         CHECKPOINT         : 0x0
    googlecompute:         WAIT_HINT          : 0x0
    googlecompute:
    googlecompute: SERVICE_NAME: docker
    googlecompute:         TYPE               : 10  WIN32_OWN_PROCESS
    googlecompute:         STATE              : 2  START_PENDING
    googlecompute:                                 (NOT_STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
    googlecompute:         WIN32_EXIT_CODE    : 0  (0x0)
    googlecompute:         SERVICE_EXIT_CODE  : 0  (0x0)
    googlecompute:         CHECKPOINT         : 0x0
    googlecompute:         WAIT_HINT          : 0x7d0
    googlecompute:         PID                : 644
    googlecompute:         FLAGS              :
    googlecompute: Ok.
    googlecompute:
    googlecompute: Stopping the Docker daemon...
    googlecompute: Setting maximum image size to 200.0GB...
    googlecompute: Starting the Docker daemon...
    googlecompute: Creating firewall rule for credential endpoint...
    googlecompute:   File "c:\python37\lib\runpy.py", line 193, in _run_module_as_main
    googlecompute:     "__main__", mod_spec)
    googlecompute:   File "c:\python37\lib\runpy.py", line 85, in _run_code
    googlecompute:     exec(code, run_globals)
    googlecompute:   File "c:\python37\Scripts\ue4-docker.exe\__main__.py", line 9, in <module>
    googlecompute:   File "c:\python37\lib\site-packages\ue4docker\main.py", line 70, in main
    googlecompute:     COMMANDS[command]['function']()
    googlecompute:   File "c:\python37\lib\site-packages\ue4docker\setup_cmd.py", line 152, in setup
    googlecompute:     _setupWindowsServer()
    googlecompute:   File "c:\python37\lib\site-packages\ue4docker\setup_cmd.py", line 106, in _setupWindowsServer
    googlecompute:     tags = requests.get('https://mcr.microsoft.com/v2/windowsfamily/windows/tags/list').json()['tags']
    googlecompute:   File "c:\python37\lib\site-packages\requests\models.py", line 889, in json
    googlecompute:     self.content.decode(encoding), **kwargs
    googlecompute:   File "c:\python37\lib\json\__init__.py", line 348, in loads
    googlecompute:     return _default_decoder.decode(s)
    googlecompute:   File "c:\python37\lib\json\decoder.py", line 337, in decode
    googlecompute:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    googlecompute:   File "c:\python37\lib\json\decoder.py", line 355, in raw_decode
    googlecompute:     raise JSONDecodeError("Expecting value", s, err.value) from None
    googlecompute: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

When I check https://mcr.microsoft.com/v2/windowsfamily/windows/tags/list which the ue4-docker setup script relies on, it seems like it no longer exists:

```
<Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:22a39cca-201e-0133-7068-ef8acc000000
Time:2019-04-10T06:40:28.4915163Z</Message></Error>
```

**Comment by hach-que** [comment]
Okay, I think the issue is just mcr.microsoft.com is down entirely, since even this doesn't work on my local PC:

```
C:\Users\jrhod\Documents\Projects\build-server-configuration\packer>docker pull mcr.microsoft.com/windows/servercore:ltsc2019
ltsc2019: Pulling from windows/servercore
no matching manifest for unknown in the manifest list entries
```

Will try getting things running later this week to see if they resolve the issue.

**Comment by adamrehn** [comment]
Thanks for letting me know about this. Evidently the URL has been changed to <https://mcr.microsoft.com/v2/windows/tags/list>.
