### ISSUE TITLE
'ue4 conan generate' fails on 5.1.0

### ISSUE THREAD

**Issue by jlsalmon** [adamrehn/ue4-docker#281]
Output of the `ue4-docker info` command:

```
ue4-docker version:         0.0.102 (latest available version is 0.0.102)
Operating system:           Linux (Ubuntu 20.04.3 LTS, 5.11.0-1028-aws)
Docker daemon version:      20.10.12
NVIDIA Docker supported:    No
Maximum image size:         No limit detected
Available disk space:       491.4 GiB
Total system memory:        30.35 GiB physical, 6.39 GiB virtual
CPU:                        8 physical, 16 logical (x86_64)
```

Building 5.1.0 fails at the `ue4 conan generate` step:

```
Copying the "ue5.1-Linux-x86_64-unknown-linux-gnu" Conan profile into a new profile named "ue4"...
Retrieving thirdparty library list from UBT...
Traceback (most recent call last):
  File "/usr/local/bin/ue4", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/ue4cli/cli.py", line 222, in main
    SUPPORTED_COMMANDS[command]['action'](manager, args)
  File "/usr/local/lib/python3.8/dist-packages/conan_ue4cli/main.py", line 48, in main
    SUBCOMMANDS[subcommand]['function'](manager, args[1:])
  File "/usr/local/lib/python3.8/dist-packages/conan_ue4cli/commands/generate.py", line 153, in generate
    libs = [lib for lib in manager.listThirdPartyLibs() if lib != 'libc++']
  File "/usr/local/lib/python3.8/dist-packages/ue4cli/UnrealManagerBase.py", line 183, in listThirdPartyLibs
    return interrogator.list(self.getPlatformIdentifier(), configuration, self._getLibraryOverrides())
  File "/usr/local/lib/python3.8/dist-packages/ue4cli/UE4BuildInterrogator.py", line 20, in list
    modules = self._getThirdPartyLibs(platformIdentifier, configuration)
  File "/usr/local/lib/python3.8/dist-packages/ue4cli/UE4BuildInterrogator.py", line 170, in _getThirdPartyLibs
    self.runUBTFunc('UnrealEditor', platformIdentifier, configuration, args)
  File "/usr/local/lib/python3.8/dist-packages/ue4cli/UnrealManagerBase.py", line 695, in <lambda>
    ubtLambda = lambda target, platform, config, args: self._runUnrealBuildTool(target, platform, config, args, True)
  File "/usr/local/lib/python3.8/dist-packages/ue4cli/UnrealManagerBase.py", line 687, in _runUnrealBuildTool
    return Utility.capture(arguments, cwd=self.getEngineRoot(), raiseOnError=True)
  File "/usr/local/lib/python3.8/dist-packages/ue4cli/Utility.py", line 125, in capture
    raise Exception(
Exception: child process ['/home/ue4/UnrealEngine/Engine/Build/BatchFiles/Linux/Build.sh', 'UnrealEditor', 'Linux', 'Development', '-Mode=JsonExport', '-OutputFile=/tmp/tmps0jdktyq/ubt_output.json'] failed with exit code 1
stdout: "Setting up bundled DotNet SDK
Running command : dotnet Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll UnrealEditor Linux Development -Mode=JsonExport -OutputFile=/tmp/tmps0jdktyq/ubt_output.json
Welcome to .NET !
---------------------
SDK Version:
Telemetry
---------
The .NET tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.
Read more about .NET CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry
----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
"
stderr: "Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
"
The command '/bin/sh -c ue4 conan generate' returned a non-zero code: 1
```

Could this have something to do with UBT needing to be pre-built?

**Comment by slonopotamus** [comment]
Please, report this to https://github.com/adamrehn/conan-ue4cli instead.

**Comment by jlsalmon** [comment]
Apologies - moved to https://github.com/adamrehn/conan-ue4cli/issues/20

**Comment by petergerten** [comment]
> Apologies - moved to [adamrehn/conan-ue4cli#20](https://github.com/adamrehn/conan-ue4cli/issues/20)

Could you solve this issues?
I tried to override the conan-ue4cli version via `-conan-ue4cli git+https://github.com/JJC1138/conan-ue4cli.git@ue5fix` via ue4docker trying these two patches: https://github.com/adamrehn/conan-ue4cli/pull/21 https://github.com/adamrehn/conan-ue4cli/pull/15 - unfortunately that did not fix the issue.

**Comment by TBBle** [comment]
Assuming there wasn't some failure to honour `-conan-ue4cli`, that suggests that the fix from those PRs is not sufficient. I at least don't know enough about conan-ue4cli to be able to say more than that.

If you just build the minimal image, and then run it up, install that version of conan-ue4cli, and execute `ue4 conan generate`, does it work? If so, then there might be something wrong with the `-conan-ue4cli` handling in ue4-docker. If not, then the fix is not sufficient, and there's nothing we can do in this repo until `conan-ue4cli` is correctly fixed.
