### ISSUE TITLE
Build faild on Windows server 2019

### ISSUE THREAD

**Issue by zhongjixiuxing** [adamrehn/ue4-docker#29]
Output of the `ue4-docker info` command:
```
ue4-docker version:         0.0.27
Operating system:           Windows Server 2019 Datacenter Evaluation Version 1809 (OS Build 17763.379)
Docker daemon version:      18.09.5
NVIDIA Docker supported:    No
Maximum image size:         200GB
Total system memory:        15.95 GiB
Number of processors:       8 physical, 16 logical

```

<br><br>

Exec command:
```
ue4-docker build 4.21.1 --no-engine
```
<br><br>

Error detail:
```
ParallelExecutor.Execute:      Creating library C:\UnrealEngine\Engine\Plugins\Runtime\Analytics\AnalyticsMulticast\Intermediate\Build\Win64\UE4Editor\Development\AnalyticsMulticast\UE4Editor-AnalyticsMulticast.lib and object C:\UnrealEngine\Engine\Plugins\Runtime\Analyt
ics\AnalyticsMulticast\Intermediate\Build\Win64\UE4Editor\Development\AnalyticsMulticast\UE4Editor-AnalyticsMulticast.exp
ParallelExecutor.Execute:   UE4Editor-FileLogging.lib
ParallelExecutor.Execute:      Creating library C:\UnrealEngine\Engine\Plugins\Runtime\Analytics\FileLogging\Intermediate\Build\Win64\UE4Editor\Development\FileLogging\UE4Editor-FileLogging.lib and object C:\UnrealEngine\Engine\Plugins\Runtime\Analytics\FileLogging\Inter
mediate\Build\Win64\UE4Editor\Development\FileLogging\UE4Editor-FileLogging.exp
Log.WriteException: ==============================================================================
Log.WriteException: ERROR: BUILD FAILED:  failed, retries not enabled:
Log.WriteException:        while executing <Compile Target="UE4Editor" Configuration="DebugGame" Platform="Win64" Arguments="-precompile -allmodules" AllowXGE="True" AllowParallelExecutor="True" Tag="#UE4Editor Win64" />
Log.WriteException:        while executing <Compile Target="UE4Editor" Configuration="Development" Platform="Win64" Arguments="-precompile -allmodules" AllowXGE="True" AllowParallelExecutor="True" Tag="#UE4Editor Win64" />
Log.WriteException:        at Engine\Build\InstalledEngineBuild.xml(122)
Log.WriteException:        (see C:\UnrealEngine\Engine\Programs\AutomationTool\Saved\Logs\Log.txt for full exception trace)
Log.WriteException:
Log.WriteException: AutomationException: BUILD FAILED:  failed, retries not enabled:
Log.WriteException:    at AutomationTool.UE4Build.Build(BuildAgenda Agenda, Nullable`1 InDeleteBuildProducts, Boolean InUpdateVersionFiles, Boolean InForceNoXGE, Boolean InUseParallelExecutor, Boolean InForceNonUnity, Boolean InForceUnity, Boolean InShowProgress, Nullabl
e`1 InChangelistNumberOverride, Dictionary`2 InTargetToManifest) in C:\UnrealEngine\Engine\Source\Programs\AutomationTool\AutomationUtils\UE4Build.cs:line 1266
Log.WriteException:    at AutomationTool.CompileTaskExecutor.Execute(JobContext Job, HashSet`1 BuildProducts, Dictionary`2 TagNameToFileSet) in C:\UnrealEngine\Engine\Source\Programs\AutomationTool\BuildGraph\Tasks\CompileTask.cs:line 160
Log.WriteException:    at AutomationTool.Node.Build(JobContext Job, Dictionary`2 TagNameToFileSet) in C:\UnrealEngine\Engine\Source\Programs\AutomationTool\BuildGraph\Node.cs:line 202
Log.WriteException:    at AutomationTool.BuildGraph.BuildNode(JobContext Job, Graph Graph, Node Node, TempStorage Storage, Boolean bWithBanner) in C:\UnrealEngine\Engine\Source\Programs\AutomationTool\BuildGraph\BuildGraph.cs:line 700
Log.WriteException:    at AutomationTool.BuildGraph.BuildAllNodes(JobContext Job, Graph Graph, TempStorage Storage) in C:\UnrealEngine\Engine\Source\Programs\AutomationTool\BuildGraph\BuildGraph.cs:line 629
Log.WriteException:    at AutomationTool.BuildGraph.Execute() in C:\UnrealEngine\Engine\Source\Programs\AutomationTool\BuildGraph\BuildGraph.cs:line 435
Log.WriteException:    at AutomationTool.Automation.Execute(List`1 CommandsToExecute, Dictionary`2 Commands) in C:\UnrealEngine\Engine\Source\Programs\AutomationTool\AutomationUtils\Automation.cs:line 563
Log.WriteException:    at AutomationTool.Automation.Process(String[] Arguments, StartupTraceListener StartupListener) in C:\UnrealEngine\Engine\Source\Programs\AutomationTool\AutomationUtils\Automation.cs:line 533
Log.WriteException:    at AutomationTool.Program.MainProc(String[] Arguments, StartupTraceListener StartupListener) in C:\UnrealEngine\Engine\Source\Programs\AutomationTool\Program.cs:line 173
Log.WriteException:    at AutomationTool.Program.<>c__DisplayClass1_0.<Main>b__2() in C:\UnrealEngine\Engine\Source\Programs\AutomationTool\Program.cs:line 99
Log.WriteException:    at AutomationTool.InternalUtils.RunSingleInstance(Func`1 Main) in C:\UnrealEngine\Engine\Source\Programs\AutomationTool\AutomationUtils\Utils.cs:line 725
Log.WriteException:    at AutomationTool.Program.Main() in C:\UnrealEngine\Engine\Source\Programs\AutomationTool\Program.cs:line 99   data: EpicGames.Context = ("while executing <Compile Target="UE4Editor" Configuration="DebugGame" Platform="Win64" Arguments="-precompile
 -allmodules" AllowXGE="True" AllowParallelExecutor="True" Tag="#UE4Editor Win64" />", "while executing <Compile Target="UE4Editor" Configuration="Development" Platform="Win64" Arguments="-precompile -allmodules" AllowXGE="True" AllowParallelExecutor="True" Tag="#UE4Edit
or Win64" />", "at Engine\Build\InstalledEngineBuild.xml(122)")
Log.WriteException: ==============================================================================
Program.Main: AutomationTool exiting with ExitCode=1 (Error_Unknown)
```

**Comment by adamrehn** [comment]
I'm not seeing any actual error details there, which suggests that an error was reported earlier in the output during the compilation of a translation unit and the build subsequently failed on a link operation that attempted to consume the object file. The two most common errors that behave this way are [fatal error LNK1318: Unexpected PDB error; OK (0)](https://adamrehn.com/docs/ue4-docker/building-images/troubleshooting-build-issues#building-the-engine-in-a-windows-container-fails-with-the-message-fatal-error-lnk1318-unexpected-pdb-error-ok-0) and [fatal error C1060: the compiler is out of heap space](https://adamrehn.com/docs/ue4-docker/building-images/troubleshooting-build-issues#building-the-engine-in-a-windows-container-fails-with-the-message-fatal-error-c1060-the-compiler-is-out-of-heap-space). If you have the complete output log, could you please look further back to see if either of these errors was emitted?
