### ISSUE TITLE
Conan Full Build Error

### ISSUE THREAD

**Issue by garunzo** [adamrehn/ue4-docker#366]
=> ERROR [conan 5/5] RUN ue4 conan generate && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite  2.7s

when running ue4-docker build 5.4.4 --target=full

**Comment by BojanV03** [comment]
I have encountered the same issue. Did you manage to fix it?

Posting additional info
`> [conan 5/5] RUN ue4 conan generate && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo '':
0.445 Using user-specified engine root: /home/ue4/UnrealEngine
2.521 Removing the "ue5.4-Linux-x86_64-unknown-linux-gnu" Conan profile if it already exists...
2.521 Removing any previous versions of profile base packages...
2.521 Creating "ue5.4-Linux-x86_64-unknown-linux-gnu" Conan profile using autodetected settings...
2.521 Installing profile base packages...
2.521 Copying the "ue5.4-Linux-x86_64-unknown-linux-gnu" Conan profile into a new profile named "ue4"...
2.521 Retrieving thirdparty library list from UBT...
2.521 Traceback (most recent call last):
2.521   File "/usr/local/bin/ue4", line 8, in <module>
2.521     sys.exit(main())
2.521   File "/usr/local/lib/python3.10/dist-packages/ue4cli/cli.py", line 222, in main
2.521     SUPPORTED_COMMANDS[command]['action'](manager, args)
2.521   File "/usr/local/lib/python3.10/dist-packages/conan_ue4cli/main.py", line 48, in main
2.521     SUBCOMMANDS[subcommand]['function'](manager, args[1:])
2.521   File "/usr/local/lib/python3.10/dist-packages/conan_ue4cli/commands/generate.py", line 153, in generate
2.521     libs = [lib for lib in manager.listThirdPartyLibs() if lib != 'libc++']
2.521   File "/usr/local/lib/python3.10/dist-packages/ue4cli/UnrealManagerBase.py", line 183, in listThirdPartyLibs
2.521     return interrogator.list(self.getPlatformIdentifier(), configuration, self._getLibraryOverrides())
2.521   File "/usr/local/lib/python3.10/dist-packages/ue4cli/UE4BuildInterrogator.py", line 20, in list
2.521     modules = self._getThirdPartyLibs(platformIdentifier, configuration)
2.521   File "/usr/local/lib/python3.10/dist-packages/ue4cli/UE4BuildInterrogator.py", line 170, in _getThirdPartyLibs
2.521     self.runUBTFunc('UnrealEditor', platformIdentifier, configuration, args)
2.521   File "/usr/local/lib/python3.10/dist-packages/ue4cli/UnrealManagerBase.py", line 695, in <lambda>
2.521     ubtLambda = lambda target, platform, config, args: self._runUnrealBuildTool(target, platform, config, args, True)
2.521   File "/usr/local/lib/python3.10/dist-packages/ue4cli/UnrealManagerBase.py", line 687, in _runUnrealBuildTool
2.522     return Utility.capture(arguments, cwd=self.getEngineRoot(), raiseOnError=True)
2.522   File "/usr/local/lib/python3.10/dist-packages/ue4cli/Utility.py", line 125, in capture
2.522     raise Exception(
2.522 Exception: child process ['/home/ue4/UnrealEngine/Engine/Build/BatchFiles/Linux/Build.sh', 'UnrealEditor', 'Linux', 'Development', '-Mode=JsonExport', '-OutputFile=/tmp/tmpm89lfgua/ubt_output.json'] failed with exit code 1
2.522 stdout: "Setting up bundled DotNet SDK
2.522 Running command : dotnet Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll UnrealEditor Linux Development -Mode=JsonExport -OutputFile=/tmp/tmpm89lfgua/ubt_output.json
2.522
2.522 Welcome to .NET !
2.522 ---------------------
2.522 SDK Version:
2.522
2.522 Telemetry
2.522 ---------
2.522 The .NET tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.
2.522
2.522 Read more about .NET CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry
2.522
2.522 ----------------
2.522 Installed an ASP.NET Core HTTPS development certificate.
2.522 To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
2.522 Learn about HTTPS: https://aka.ms/dotnet-https
2.522 ----------------
2.522 Write your first app: https://aka.ms/dotnet-hello-world
2.522 Find out what's new: https://aka.ms/dotnet-whats-new
2.522 Explore documentation: https://aka.ms/dotnet-docs
2.522 Report issues and find source on GitHub: https://github.com/dotnet/core
2.522 Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
2.522 --------------------------------------------------------------------------------------
2.522 "
2.522 stderr: "Could not execute because the specified command or file was not found.
2.522 Possible reasons for this include:
2.522   * You misspelled a built-in dotnet command.
2.522   * You intended to execute a .NET program, but dotnet-Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll does not exist.
2.522   * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
2.522 "
------
Dockerfile:20
--------------------
  18 |     # Extract the third-party library details from UBT
  19 |     RUN ue4 setroot /home/ue4/UnrealEngine && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''
  20 | >>> RUN ue4 conan generate && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''
  21 |
  22 |     # Copy the generated Conan packages into a new image with our Installed Build
--------------------
ERROR: failed to solve: process "/bin/sh -c ue4 conan generate && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''" did not complete successfully: exit code: 1
[ue4-docker build] Error: failed to build image "adamrehn/ue4-full:5.4.4-opengl-ubuntu22.04".`

**Comment by TBBle** [comment]
Hmm. We're just calling out to UE's `Build.sh`, so it _looks_ like a UE-side issue, but perhaps we need to do something to ensure that .dll exists first...

Also, poking around, there used to be an issue [that `UnrealBuildTool.dll` was in the wrong directory](https://qiita.com/_akoto_/items/f91a9e52d6e1f904bb78#%E5%AF%BE%E5%BF%9C%E3%81%97%E3%81%9F%E4%BA%8B) (or perhaps the [Build.sh has a faulty default for installed builds](https://forums.unrealengine.com/t/generate-cpp-project-couldnt-find-unrealbuildtool/231288/42)... although this might be unrelated and was also years ago.)

And of course, it might be a new issue with UE 5.4.4, that we would have to work-around or patch. UE 5.5.0 is out now, so we may never see a UE 5.4.5 if it is an engine-side bug; it'd be good to know if this is also affecting UE 5.5.0.

I don't have a Linux box handy to investigate this right now, but if anyone's up for debugging, determining if there is a `UnrealBuildTool.dll` created before this step, and if so, where it's located, would help narrow down the issue.
