### ISSUE TITLE
ERROR: Environment variable 'BinaryOutputDir' is not defined

### ISSUE THREAD

**Issue by ShiroiKuma** [adamrehn/ue4-docker#65]
Output of the `ue4-docker info` command:

```
ue4-docker version:         0.0.47 (latest available version is 0.0.47)
Operating system:           Windows Server 2019 Standard Version 1809 (OS Build 17763.107)
Docker daemon version:      19.03.5
NVIDIA Docker supported:    No
Maximum image size:         200GB
Available disk space:       370.43 GiB
Total system memory:        8 GiB physical, 15.55 GiB virtual
Number of processors:       8 physical, 8 logical
```

ue4-docker build 4.24.2 --no-engine --exclude debug

Building the current engine version using the above command results in the following error:

```
Step 9/16 : RUN ue4 conan generate && ue4 conan generate --remove-only && echo. && echo.RUN directive complete. Docker will now commit the filesystem layer to disk. && echo.Note that for large filesystem layers this can take quite some time. && echo.Performing filesystem layer commit... && echo.
 ---> Running in 9416f34b34a4
Removing the "ue4" Conan profile if it already exists...
Removing any previous versions of profile base packages...
Creating "ue4" Conan profile using autodetected settings...
Installing profile base packages...
Retrieving thirdparty library list from UBT...
Using user-specified engine root: C:\UnrealEngine
Traceback (most recent call last):
  File "c:\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37\Scripts\ue4.exe\__main__.py", line 9, in <module>
  File "c:\python37\lib\site-packages\ue4cli\cli.py", line 216, in main
    SUPPORTED_COMMANDS[command]['action'](manager, args)
  File "c:\python37\lib\site-packages\conan_ue4cli\main.py", line 34, in main
    SUBCOMMANDS[subcommand]['function'](manager, args[1:])
  File "c:\python37\lib\site-packages\conan_ue4cli\generate.py", line 197, in generate
    libs = [lib for lib in manager.listThirdPartyLibs() if lib != 'libc++']
  File "c:\python37\lib\site-packages\ue4cli\UnrealManagerBase.py", line 178, in listThirdPartyLibs
    return interrogator.list(self.getPlatformIdentifier(), configuration, self._getLibraryOverrides())
  File "c:\python37\lib\site-packages\ue4cli\UE4BuildInterrogator.py", line 20, in list
    modules = self._getThirdPartyLibs(platformIdentifier, configuration)
  File "c:\python37\lib\site-packages\ue4cli\UE4BuildInterrogator.py", line 156, in _getThirdPartyLibs
    self.runUBTFunc('UE4Editor', platformIdentifier, configuration, args)
  File "c:\python37\lib\site-packages\ue4cli\UnrealManagerBase.py", line 641, in <lambda>
    ubtLambda = lambda target, platform, config, args: self._runUnrealBuildTool(target, platform, config, args, True)
  File "c:\python37\lib\site-packages\ue4cli\UnrealManagerBase.py", line 633, in _runUnrealBuildTool
    return Utility.capture(arguments, cwd=self.getEngineRoot(), raiseOnError=True)
  File "c:\python37\lib\site-packages\ue4cli\Utility.py", line 129, in capture
    '\nstderr: "' + stderr + '"'
Exception: child process ['C:\\UnrealEngine\\Engine\\Build\\BatchFiles\\Build.bat', 'UE4Editor', 'Win64', 'Development', '-Mode=JsonExport', '-OutputFile=C:\\Users\\ContainerAdministrator\\AppData\\Local\\Temp\\tmpko3c1he4\\ubt_output.json'] failed with exit code 5
stdout: "Writing C:\Users\ContainerAdministrator\AppData\Local\Temp\tmpko3c1he4\ubt_output.json...
ERROR: Environment variable 'BinaryOutputDir' is not defined (referenced by C:\UnrealEngine\Engine\Plugins\Experimental\AlembicImporter\Source\ThirdParty\Alembic\AlembicLib.Build.cs)
"
stderr: ""
The command 'cmd /S /C ue4 conan generate && ue4 conan generate --remove-only && echo. && echo.RUN directive complete. Docker will now commit the filesystem layer to disk. && echo.Note that for large filesystem layers this can take quite some time. && echo.Performing filesystem layer commit... && echo.' returned a non-zero code: 1
[ue4-docker build] Error: failed to build image "adamrehn/ue4-full:4.24.2-ltsc2019".
```

**Comment by adamrehn** [comment]
Thanks for reporting this, I'll investigate further.

**Comment by ShiroiKuma** [comment]
I've cleaned all docker images, and I'm currently building with the following one more time (since about 8 hours ago), just to make sure it's replicable consistently.

```ue4-docker build 4.24.2 --exclude debug```

I feel bad for the reports this weekend, back to back. Once I've got Windows 2019 done, I'll be moving onto Linux and OSX builds afterwards. One at a time... :)

**Comment by ShiroiKuma** [comment]
I nuked all images, cleaned source and rebuilt over the last 5 days with the following:

`ue4-docker build 4.24.2 --monitor --no-engine --exclude debug --exclude templates`

And the exact same error regarding BuildOutputDir is still present.

**Comment by adamrehn** [comment]
It turns out this is actually caused by a bug in UnrealBuildTool itself that prevents its JSON output mode from functioning correctly. I've added code in ue4-docker version 0.0.49 that automatically patches UBT, and will be submitting a pull request to Epic with the fix as well.

**Comment by ShiroiKuma** [comment]
Thanks for looking into this and adding that patch. I'm rebuilding on both Windows and Linux servers currently with this new version (from scratch) and will let you know how that goes.

**Comment by adamrehn** [comment]
You might want to cancel those builds and quickly update to ue4-docker version 0.0.50 first, which fixes issue #66.

**Comment by ShiroiKuma** [comment]
Just saw that and restarted.

**Comment by adamrehn** [comment]
The pull request is now submitted: https://github.com/EpicGames/UnrealEngine/pull/6674

**Comment by ShiroiKuma** [comment]
I can confirm both linux and windows build successfully now.
