### ISSUE TITLE
Linux Build 4.24.2 Fails with NoneType on config

### ISSUE THREAD

**Issue by ShiroiKuma** [adamrehn/ue4-docker#66]
Output of the `ue4-docker info` command:

```
ue4-docker version:         0.0.48 (latest available version is 0.0.48)
Operating system:           Linux (Debian GNU/Linux 10 (buster), 4.19.0-6-amd64)
Docker daemon version:      19.03.5
NVIDIA Docker supported:    No
Maximum image size:         No limit detected
Available disk space:       327.82 GiB
Total system memory:        7.79 GiB physical, 8 GiB virtual
Number of processors:       4 physical, 8 logical
```

Build command:

```
ue4-docker build 4.24.2 --monitor --no-engine --exclude debug --exclude templates
```

Error:

```
[ue4-docker build] LINUX CONTAINER SETTINGS
[ue4-docker build] Building GPU-enabled images compatible with NVIDIA Docker (OpenGL support).

[ue4-docker build] GENERAL SETTINGS
[ue4-docker build] Excluding the following Engine components:
[ue4-docker build] - Debug symbols
[ue4-docker build] - Template projects and samples
[ue4-docker build] Not building the ue4-source image, no Git credentials required.
[ue4-docker build] [2020-02-09 09:10:14] [Available disk: 327.82 GiB] [Available memory: 1.22 GiB physical, 7.93 GiB virtual] [CPU usage: 0.00%]

[ue4-docker build] Image "adamrehn/ue4-build-prerequisites:opengl" exists and rebuild not requested, skipping build.

[ue4-docker build] Image "adamrehn/ue4-source:4.24.2-opengl" exists and rebuild not requested, skipping build.

[ue4-docker build] User specified `--no-engine`, skipping ue4-engine image build.

[ue4-docker build] Image "adamrehn/ue4-minimal:4.24.2-opengl" exists and rebuild not requested, skipping build.

[ue4-docker build] Building image "adamrehn/ue4-full:4.24.2-opengl"...
Sending build context to Docker daemon  8.192kB
Step 1/28 : ARG NAMESPACE
Step 2/28 : ARG TAG
Step 3/28 : ARG PREREQS_TAG
Step 4/28 : FROM ${NAMESPACE}/ue4-source:${TAG}-${PREREQS_TAG} AS builder
 ---> 513c89f4a36f
Step 5/28 : USER root
 ---> Using cache
 ---> a74c652b0d4e
Step 6/28 : RUN pip3 install setuptools wheel && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''
 ---> Using cache
 ---> 23e4c4d245bb
Step 7/28 : RUN pip3 install ue4cli conan-ue4cli && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''
 ---> Using cache
 ---> fd7fa3937cf4
Step 8/28 : USER ue4
 ---> Using cache
 ---> e4cb4cb1d3c9
Step 9/28 : RUN ue4 setroot /home/ue4/UnrealEngine && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''
 ---> Using cache
 ---> b52c8544dfdf
Step 10/28 : RUN ue4 conan generate && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''
 ---> Using cache
 ---> 213911a5da64
Step 11/28 : FROM ${NAMESPACE}/ue4-minimal:${TAG}-${PREREQS_TAG}
 ---> 7d2163b41838
Step 12/28 : RUN git clone "https://github.com/adamrehn/UE4Capture.git" /home/ue4/UE4Capture && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''
 ---> Using cache
 ---> e38647347670
Step 13/28 : USER root
 ---> Using cache
 ---> 64bf1b1e7fb4
Step 14/28 : RUN apt-get update && apt-get install -y --no-install-recommends cmake && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''
 ---> Using cache
 ---> 2d1b77b73ed0
Step 15/28 : RUN pip3 install setuptools wheel && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''
 ---> Using cache
 ---> c64044b0de34
Step 16/28 : RUN pip3 install ue4cli conan-ue4cli ue4-ci-helpers && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''
 ---> Using cache
 ---> 8c94d551a18c
Step 17/28 : USER ue4
 ---> Using cache
 ---> c89bf80b2ef8
Step 18/28 : COPY --from=builder --chown=ue4:ue4 /home/ue4/.conan /home/ue4/.conan
 ---> Using cache
 ---> 6e9bb1f78640
Step 19/28 : RUN ue4 setroot /home/ue4/UnrealEngine && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''
 ---> Using cache
 ---> 105bef8d7af8
Step 20/28 : RUN ue4 conan generate --profile-only && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''
 ---> Using cache
 ---> 001ae7dab61b
Step 21/28 : RUN ue4 conan build MediaIPC-ue4 && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''
 ---> Running in eb5dce673933
Using user-specified engine root: /home/ue4/UnrealEngine
Updating the recipe cache...
Traceback (most recent call last):
  File "/usr/local/bin/ue4", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/ue4cli/cli.py", line 216, in main
    SUPPORTED_COMMANDS[command]['action'](manager, args)
  File "/usr/local/lib/python3.6/dist-packages/conan_ue4cli/main.py", line 34, in main
    SUBCOMMANDS[subcommand]['function'](manager, args[1:])
  File "/usr/local/lib/python3.6/dist-packages/conan_ue4cli/build.py", line 302, in build
    update(manager, argv)
  File "/usr/local/lib/python3.6/dist-packages/conan_ue4cli/update.py", line 7, in update
    RecipeCache.updateCache()
  File "/usr/local/lib/python3.6/dist-packages/conan_ue4cli/RecipeCache.py", line 36, in updateCache
    tools.get(RECIPE_ZIP_URL, destination=parentDir)
  File "/usr/local/lib/python3.6/dist-packages/conans/tools.py", line 81, in get
    return tools_net.get(output=_global_output, requester=_global_requester, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/conans/client/tools/net.py", line 21, in get
    md5=md5, sha1=sha1, sha256=sha256)
  File "/usr/local/lib/python3.6/dist-packages/conans/client/tools/net.py", line 58, in download
    retry = retry if retry is not None else config.retry
AttributeError: 'NoneType' object has no attribute 'retry'
The command '/bin/sh -c ue4 conan build MediaIPC-ue4 && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''' returned a non-zero code: 1
[ue4-docker build] Error: failed to build image "adamrehn/ue4-full:4.24.2-opengl".
```

**Comment by ShiroiKuma** [comment]
This is being built in a freshly installed Debian 10.2 VirtualMachine running no a server without a GPU. Not sure if that's related, but it did get all the way to the full image as you can see above.

**Comment by ShiroiKuma** [comment]
Modifying the Dockerfile to add ```RUN pip3 install conan==1.21.0``` before ```RUN pip3 install ue4cli conan-ue4cli``` (both locations) resolves the problem
