### ISSUE TITLE
Any ue4-docker command not works ,really need some help.

### ISSUE THREAD

**Issue by fvmitnick** [adamrehn/ue4-docker#72]
Myt system is Ubuntu 16.04 ,After install pip3 ,i use any docker command that i get the info like this : 

nick@NickLinux:~/Downloads$ ue4-docker version
Traceback (most recent call last):
  File "/usr/local/bin/ue4-docker", line 7, in <module>
    from ue4docker import main
  File "/usr/local/lib/python3.5/dist-packages/ue4docker/__init__.py", line 1, in <module>
    from .build import build
  File "/usr/local/lib/python3.5/dist-packages/ue4docker/build.py", line 2, in <module>
    from .infrastructure import *
  File "/usr/local/lib/python3.5/dist-packages/ue4docker/infrastructure/__init__.py", line 2, in <module>
    from .CredentialEndpoint import CredentialEndpoint
  File "/usr/local/lib/python3.5/dist-packages/ue4docker/infrastructure/CredentialEndpoint.py", line 1, in <module>
    import logging, multiprocessing, os, platform, secrets, time, urllib.parse
ImportError: No module named 'secrets'

i also pinned pip3 -V info :
nick@NickLinux:~/Downloads$ pip3 -V
pip 20.0.2 from /usr/local/lib/python3.5/dist-packages/pip (python 3.5)

Hope someone can give me some advice , thx : )

**Comment by adamrehn** [comment]
That's odd that pip actually allowed you to install the ue4-docker package using Python 3.5, since the package's metadata [sets Python 3.6 as the minimum required version](https://github.com/adamrehn/ue4-docker/blob/v0.0.54/setup.py#L37). Your output lists the pip version as 20.0.2, and pip has supported the `python_requires` flag since version 9.0.0. Very strange indeed.
